# KT Rounding Algorithm 

In [1]:
import numpy as np
import pandas as pd
import random

### 1. Data initialization & Indexing

- Assume that the optimal solution of the concave problem (5) is received as a numpy array of size (n*m) where n is the number of agents and m is the number of items. 
<br><br>
- Then convert the solution as Pandas DataFrame in order to index each row and column of the solution matrix.


In [22]:
# num_agents : Number of agents
# num_items  : Number of items
# x          : Solution vector of the convex problem

num_agents = 5 
num_items = 3  

x = np.mat([1,0.25,0,0.33,0.6,0,0.4,0,0.33,0.2,0,0.35,1,0.33,0.2])
x = np.reshape(x, (num_agents,num_items), order = 'F')

x = pd.DataFrame(x)
x.head()

0     1     2
0  1.00  0.00  0.00
1  0.25  0.40  0.35
2  0.00  0.00  1.00
3  0.33  0.33  0.33
4  0.60  0.20  0.20

In [23]:
#n : Set of agents that are represented by incrementing alphabetical characters
#m : Set of items that are represented by incrementing integer numbers

# initialize both n and m as empty sets
n = set({}) 
m = set({})

# add elements to set n and m
n_count, m_count = x.shape 

n_elem = 'a'
m_elem = '1'

while (len(n) < n_count):
    n.add(n_elem)
    n_elem = chr(ord(n_elem) + 1)
    
while (len(m) < m_count):
    m.add(m_elem)
    m_elem = str(int(m_elem)+1)
    
# convert sets to lists and use them as index of the DataFrame x
index_names = sorted(list(n))
column_names = sorted(list(m))

x.index = index_names
x.columns = column_names

x.head()

1     2     3
a  1.00  0.00  0.00
b  0.25  0.40  0.35
c  0.00  0.00  1.00
d  0.33  0.33  0.33
e  0.60  0.20  0.20

### 2. Apply Algorithm

- During the course of algorithm, initialize $S$ be the set of allocated agents and $S_{i}$ be the set of alocated item i. They are both initialized as $\emptyset$.
<br><br>
- While $S \neq [n]$, select $i \in [m], \theta \in [0, 1]$ uniformly at random. Let $S_{i}^{\theta} = \{j \in [n] \setminus S : x_{ji} \ge \theta\}$, and update $S_{i} \gets S_{i} \cup S_{i}^{\theta}$ and $S \gets S \cup S_{i}^{\theta}$.
<br><br>
- Return $S_{1},.....,S_{m}$

In [24]:
# S   : Set S initialized as an empty set
# S_i : Dictionary of set where keys are item i, and values are set of agents that are allocated item i. All sets are 
#       initialized as empty set. 

S = set({})
S_i = {}

# initialize an empty set for each item i
for i in m:
    S_i[i] = set({})
    
while (S != n):
    m = list(m)
    i = random.choice(m)
    theta = float(np.random.uniform(0,1,1)) # select random number theta from uniform distribution [0,1]
    S_theta = set({})
    # within row i, add element to S_theta iif its value is equal or greater than theta
    col_i = x[i]
    for idx in col_i.index:
        if idx not in S:
            if col_i[idx] >= theta:
                S_theta.add(idx)
    # merge S_theta to S and S_i        
    S = S.union(S_theta)
    S_i[i] = S_i[i].union(S_theta)

In [43]:
S_i = dict(sorted(S_i.items()))
print(S_i)
print(S)
item_list = sorted(list(S_i.keys()))
agent_list = sorted(list(S))

print(item_list)
print(agent_list)

output = pd.DataFrame(columns = item_list, index = agent_list)
output.head()

for k in S_i.keys():
    for v in list(S_i[k]):
    
        output[k][v] = 1
output = output.fillna(0)
output = np.array(output)
print(output)


{'1': {'a'}, '2': set(), '3': {'e', 'd', 'b', 'c'}}
{'c', 'e', 'a', 'b', 'd'}
['1', '2', '3']
['a', 'b', 'c', 'd', 'e']
[[1 0 0]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]]
